In [2]:
import pandas as pd
from datetime import datetime, timedelta
!pip install geopandas
!pip install gtfs_functions
from gtfs_functions import Feed, map_gdf
import datetime

Requirement already satisfied: geopandas in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (0.13.2)
Requirement already satisfied: fiona>=1.8.19 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas) (1.9.4.post1)
Requirement already satisfied: packaging in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas) (23.1)
Requirement already satisfied: pandas>=1.1.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas) (1.5.3)
Requirement already satisfied: pyproj>=3.0.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas) (3.6.0)
Requirement already satisfied: shapely>=1.7.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas) (2023.7.22)
Requirement already satisfied: click~=8.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas) (8.1.6)
Requirement already satisfied: click-plugins>=1.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas) (1.1.1)
Requirement already satisfied: cligj>=0.5 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas) (0.7.2)
Requirement already satisfied: six in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from pandas>=1.1.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from pandas>=1.1.0->geopandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from pandas>=1.1.0->geopandas) (1.25.2)
Requirement already satisfied: colorama in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from click~=8.0->fiona>=1.8.19->geopandas) (0.4.6)
Requirement already satisfied: gtfs_functions in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (2.0.4)
Requirement already satisfied: branca>=0.6.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (0.6.0)
Requirement already satisfied: folium>=0.14.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (0.14.0)
Requirement already satisfied: geopandas>=0.12.2 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (0.13.2)
Requirement already satisfied: jenkspy>=0.3.2 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (0.3.3)
Requirement already satisfied: numpy>=1.24.2 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (1.25.2)
Requirement already satisfied: pandas==1.5.3 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (1.5.3)
Requirement already satisfied: pendulum>=2.0.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (2.1.2)
Requirement already satisfied: plotly>=5.13.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (5.15.0)
Requirement already satisfied: shapely>=2.0.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (2.0.1)
Requirement already satisfied: unicode>=2.9 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (2.9)
Requirement already satisfied: utm>=0.7.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from gtfs_functions) (0.7.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from pandas==1.5.3->gtfs_functions) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from pandas==1.5.3->gtfs_functions) (2023.3)
Requirement already satisfied: jinja2 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from branca>=0.6.0->gtfs_functions) (3.1.2)
Requirement already satisfied: requests in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from folium>=0.14.0->gtfs_functions) (2.31.0)
Requirement already satisfied: fiona>=1.8.19 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas>=0.12.2->gtfs_functions) (1.9.4.post1)
Requirement already satisfied: packaging in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas>=0.12.2->gtfs_functions) (23.1)
Requirement already satisfied: pyproj>=3.0.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from geopandas>=0.12.2->gtfs_functions) (3.6.0)
Requirement already satisfied: pytzdata>=2020.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from pendulum>=2.0.0->gtfs_functions) (2020.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from plotly>=5.13.0->gtfs_functions) (8.2.2)
Requirement already satisfied: attrs>=19.2.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (23.1.0)
Requirement already satisfied: certifi in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (2023.7.22)
Requirement already satisfied: click~=8.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (8.1.6)
Requirement already satisfied: click-plugins>=1.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (1.1.1)
Requirement already satisfied: cligj>=0.5 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (0.7.2)
Requirement already satisfied: six in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from jinja2->branca>=0.6.0->gtfs_functions) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from requests->folium>=0.14.0->gtfs_functions) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from requests->folium>=0.14.0->gtfs_functions) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from requests->folium>=0.14.0->gtfs_functions) (2.0.4)
Requirement already satisfied: colorama in c:\users\sd\anaconda3\envs\gtfs-env\lib\site-packages (from click~=8.0->fiona>=1.8.19->geopandas>=0.12.2->gtfs_functions) (0.4.6)

In [3]:
from gtfs_functions import Feed, map_gdf

In [4]:
# Load GTFS data into DataFrames
feed = Feed(r'C:\Users\sd\OneDrive\Indicateur TC\GTFS.zip',time_windows=[0, 6, 9, 15, 19, 22, 24], busiest_date= False)
calendar_df = feed.calendar_dates
stop_times_df = feed.stop_times

INFO:root:Reading "calendar_dates.txt".

INFO:root:get trips in stop_times
INFO:root:accessing trips
INFO:root:Reading "routes.txt".
INFO:root:Reading "trips.txt".
INFO:root:_trips is defined in stop_times
INFO:root:Reading "stops.txt".
INFO:root:Reading "stop_times.txt".
INFO:root:computing patterns
INFO:root:Reading "stop_times.txt".

In [5]:
from datetime import timedelta

In [6]:
# Merge the data to have the dates on it
merged_data = pd.merge(stop_times_df, calendar_df, on='service_id')

# Convert all dates to a consistent format (e.g., YYYY-MM-DD)
merged_data['date'] = pd.to_datetime(merged_data['date'], format='%Y%m%d', errors='coerce')

In [7]:
# Step 1: Convert 'arrival_time' column to timedeltas
merged_data['arrival_time'] = merged_data['arrival_time'].apply(lambda x: timedelta(seconds=x))

# Step 2: Subtract the timedelta for 3:45 AM
start_time = timedelta(hours=3, minutes=45)
merged_data['adjusted_time'] = merged_data['arrival_time'] - start_time

# Step 3: Combine hours, minutes, and seconds into a single column
merged_data['time_in_hhmmss'] = merged_data['adjusted_time'].apply(lambda x: str(x))

merged_data[['time_in_hhmmss']]

          time_in_hhmmss
0        0 days 14:11:00
1        0 days 14:11:00
2        0 days 14:11:00
3        0 days 14:11:00
4        0 days 14:11:00
...                  ...
4866791  0 days 05:19:00
4866792  0 days 05:19:00
4866793  0 days 05:19:00
4866794  0 days 05:19:00
4866795  0 days 05:19:00

[4866796 rows x 1 columns]

In [8]:
calendar_df

        service_id      date  exception_type
0          1112527  20230807               1
1          1112527  20230808               1
2          1112527  20230809               1
3          1112527  20230810               1
4          1112527  20230811               1
...            ...       ...             ...
185734  38_1109181  20230826               1
185735  38_1109181  20230902               1
185736   38_935884  20230812               1
185737   38_935884  20230819               1
185738   38_935884  20230826               1

[185739 rows x 3 columns]

In [9]:
stop_times_df

,trip_id,route_id,pattern,route_name,service_id,direction_id,shape_id,arrival_time,departure_time,stop_id,...,timepoint,stop_headsign,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,geometry
0,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,64560.0,64560.0,stop_point:SP_1831,...,1,NaN,40001.0,Basso Cambo,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007)
1,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,64620.0,64620.0,stop_point:SP_3411,...,1,NaN,40010.0,Bellefontaine,43.566281,1.398946,0,stop_area:SA_1011,1,POINT (1.39895 43.56628)
2,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,64680.0,64680.0,stop_point:SP_3069,...,1,NaN,40020.0,Reynerie,43.570226,1.401999,0,stop_area:SA_1343,1,POINT (1.40200 43.57023)
3,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,64800.0,64800.0,stop_point:SP_264,...,1,NaN,40030.0,Mirail-Université,43.574696,1.402199,0,stop_area:SA_545,1,POINT (1.40220 43.57470)
4,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,64860.0,64860.0,stop_point:SP_2569,...,1,NaN,40040.0,Bagatelle,43.579871,1.412438,0,stop_area:SA_1765,1,POINT (1.41244 43.57987)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444452,1735223,line:217,fa8fbdaee438cf4a0a,321 Frouzins Tréville / Portet Gare SNCF,35_1072086,1,10543,32280.0,32280.0,stop_point:SP_5149,...,1,NaN,29035.0,F. Mitterrand,43.524950,1.323034,0,stop_area:SA_443,1,POINT (1.32303 43.52495)
444453,1735223,line:217,fa8fbdaee438cf4a0a,321 Frouzins Tréville / Portet Gare SNCF,35_1072086,1,10543,32340.0,32340.0,stop_point:SP_3028,...,1,NaN,29021.0,Painlevé,43.521867,1.321476,0,stop_area:SA_1165,1,POINT (1.32148 43.52187)
444454,1735223,line:217,fa8fbdaee438cf4a0a,321 Frouzins Tréville / Portet Gare SNCF,35_1072086,1,10543,32400.0,32400.0,stop_point:SP_3124,...,1,NaN,29011.0,Collège Picasso,43.520179,1.320252,0,stop_area:SA_227,1,POINT (1.32025 43.52018)
444455,1735223,line:217,fa8fbdaee438cf4a0a,321 Frouzins Tréville / Portet Gare SNCF,35_1072086,1,10543,32520.0,32520.0,stop_point:SP_5145,...,1,NaN,36241.0,Rouget de Lisle,43.520932,1.316114,0,stop_area:SA_2456,1,POINT (1.31611 43.52093)
444456,1735223,line:217,fa8fbdaee438cf4a0a,321 Frouzins Tréville / Portet Gare SNCF,35_1072086,1,10543,32640.0,32640.0,stop_point:SP_5147,...,1,NaN,36250.0,Frouzins Tréville,43.525522,1.311828,0,stop_area:SA_2455,1,POINT (1.31183 43.52552)

In [10]:
merged_data[(merged_data['service_id']=='27_1053506')&(merged_data['parent_station']=='stop_area:SA_206')].sort_values('date')

,trip_id,route_id,pattern,route_name,service_id,direction_id,shape_id,arrival_time,departure_time,stop_id,...,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,geometry,date,exception_type,adjusted_time,time_in_hhmmss
0,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-07,1,0 days 14:11:00,0 days 14:11:00
1,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-08,1,0 days 14:11:00,0 days 14:11:00
2,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-09,1,0 days 14:11:00,0 days 14:11:00
3,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-10,1,0 days 14:11:00,0 days 14:11:00
4,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-12,1,0 days 14:11:00,0 days 14:11:00
5,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-14,1,0 days 14:11:00,0 days 14:11:00
6,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-15,1,0 days 14:11:00,0 days 14:11:00
7,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-16,1,0 days 14:11:00,0 days 14:11:00
8,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-17,1,0 days 14:11:00,0 days 14:11:00
9,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-19,1,0 days 14:11:00,0 days 14:11:00
10,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-21,1,0 days 14:11:00,0 days 14:11:00
11,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-22,1,0 days 14:11:00,0 days 14:11:00
12,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-23,1,0 days 14:11:00,0 days 14:11:00
13,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-24,1,0 days 14:11:00,0 days 14:11:00
14,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-26,1,0 days 14:11:00,0 days 14:11:00
15,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-28,1,0 days 14:11:00,0 days 14:11:00
16,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-29,1,0 days 14:11:00,0 days 14:11:00
17,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-30,1,0 days 14:11:00,0 days 14:11:00
18,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-08-31,1,0 days 14:11:00,0 days 14:11:00
19,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-09-01,1,0 days 14:11:00,0 days 14:11:00
20,1714449,line:61,ab9f503412585d2d8d,A Basso Cambo / Balma - Gramont,27_1053506,0,10437,0 days 17:56:00,64560.0,stop_point:SP_1831,...,43.570072,1.392213,0,stop_area:SA_206,1,POINT (1.39221 43.57007),2023-09-02,1,0 days 14:11:00,0 days 14:11:00

In [11]:
merged_data[(merged_data['parent_station']=='stop_area:SA_206')].sort_values(['service_id','stop_name','date','arrival_time'])

,trip_id,route_id,pattern,route_name,service_id,direction_id,shape_id,arrival_time,departure_time,stop_id,...,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding,geometry,date,exception_type,adjusted_time,time_in_hhmmss
3148942,1805390,line:22,2cc8f5ef45a17a4a74,48 Basso Cambo / Tournefeuille Lycée,1122864,1,11097,0 days 09:17:00,33420.0,stop_point:SP_4009,...,43.569423,1.392455,0,stop_area:SA_206,1,POINT (1.39245 43.56942),2023-08-12,1,0 days 05:32:00,0 days 05:32:00
3148943,1805390,line:22,2cc8f5ef45a17a4a74,48 Basso Cambo / Tournefeuille Lycée,1122864,1,11097,0 days 09:17:00,33420.0,stop_point:SP_4009,...,43.569423,1.392455,0,stop_area:SA_206,1,POINT (1.39245 43.56942),2023-08-19,1,0 days 05:32:00,0 days 05:32:00
3148944,1805390,line:22,2cc8f5ef45a17a4a74,48 Basso Cambo / Tournefeuille Lycée,1122864,1,11097,0 days 09:17:00,33420.0,stop_point:SP_4009,...,43.569423,1.392455,0,stop_area:SA_206,1,POINT (1.39245 43.56942),2023-08-26,1,0 days 05:32:00,0 days 05:32:00
3163453,1805394,line:22,2cc8f5ef45a17a4a74,48 Basso Cambo / Tournefeuille Lycée,1122867,1,11097,0 days 11:17:00,40620.0,stop_point:SP_4009,...,43.569423,1.392455,0,stop_area:SA_206,1,POINT (1.39245 43.56942),2023-08-12,1,0 days 07:32:00,0 days 07:32:00
3163454,1805394,line:22,2cc8f5ef45a17a4a74,48 Basso Cambo / Tournefeuille Lycée,1122867,1,11097,0 days 11:17:00,40620.0,stop_point:SP_4009,...,43.569423,1.392455,0,stop_area:SA_206,1,POINT (1.39245 43.56942),2023-08-19,1,0 days 07:32:00,0 days 07:32:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65734,1865724,line:61,2a7f6492c182a7af39,A Basso Cambo / Balma - Gramont,27_1147512,1,10438,1 days 01:45:00,92700.0,stop_point:SP_3055,...,43.570074,1.392336,0,stop_area:SA_206,1,POINT (1.39234 43.57007),2023-08-11,1,0 days 22:00:00,0 days 22:00:00
65735,1865724,line:61,2a7f6492c182a7af39,A Basso Cambo / Balma - Gramont,27_1147512,1,10438,1 days 01:45:00,92700.0,stop_point:SP_3055,...,43.570074,1.392336,0,stop_area:SA_206,1,POINT (1.39234 43.57007),2023-08-18,1,0 days 22:00:00,0 days 22:00:00
158254,1865725,line:61,2a7f6492c182a7af39,A Basso Cambo / Balma - Gramont,27_1147513,1,10438,1 days 02:21:00,94860.0,stop_point:SP_3055,...,43.570074,1.392336,0,stop_area:SA_206,1,POINT (1.39234 43.57007),2023-08-11,1,0 days 22:36:00,0 days 22:36:00
158255,1865725,line:61,2a7f6492c182a7af39,A Basso Cambo / Balma - Gramont,27_1147513,1,10438,1 days 02:21:00,94860.0,stop_point:SP_3055,...,43.570074,1.392336,0,stop_area:SA_206,1,POINT (1.39234 43.57007),2023-08-18,1,0 days 22:36:00,0 days 22:36:00
182735,1868339,line:61,2a7f6492c182a7af39,A Basso Cambo / Balma - Gramont,27_1147526,1,10438,0 days 22:51:00,82260.0,stop_point:SP_3055,...,43.570074,1.392336,0,stop_area:SA_206,1,POINT (1.39234 43.57007),2023-08-13,1,0 days 19:06:00,0 days 19:06:00

In [12]:
merged_data.drop_duplicates('')

KeyError: Index([''], dtype='object')

In [ ]:
table_dates = merged_data[['parent_station','date','arrival_time','stop_id','stop_name']].groupby(['parent_station','date']).agg(
    arrival_time_max=pd.NamedAgg(column="arrival_time", aggfunc="max"),
    arrival_time_min=pd.NamedAgg(column="arrival_time", aggfunc="min"),
    stop_name=pd.NamedAgg(column="stop_name", aggfunc="max")).reset_index()

In [ ]:
table_dates['Amplitude en minutes'] = ((table_dates['arrival_time_max'] - table_dates['arrival_time_min']) / (60*10080)*100)
table_dates

,parent_station,date,arrival_time_max,arrival_time_min,stop_name,Amplitude en minutes
0,stop_area:SA_1,2023-08-07,73800.0,25200.0,Montjoie,8.035714
1,stop_area:SA_1,2023-08-08,73800.0,25200.0,Montjoie,8.035714
2,stop_area:SA_1,2023-08-09,73800.0,25200.0,Montjoie,8.035714
3,stop_area:SA_1,2023-08-10,73800.0,25200.0,Montjoie,8.035714
4,stop_area:SA_1,2023-08-11,73800.0,25200.0,Montjoie,8.035714
...,...,...,...,...,...,...
42729,stop_area:SA_999,2023-08-28,75180.0,20880.0,Lancefoc,8.978175
42730,stop_area:SA_999,2023-08-29,75180.0,20880.0,Lancefoc,8.978175
42731,stop_area:SA_999,2023-08-30,75180.0,20880.0,Lancefoc,8.978175
42732,stop_area:SA_999,2023-08-31,75180.0,20880.0,Lancefoc,8.978175
42733,stop_area:SA_999,2023-09-01,75180.0,20880.0,Lancefoc,8.978175

In [ ]:
# Parameteres su ArcGIS tool
date_debut = '2023-08-07'
date_fin = '2023-08-13'

# Flter to have only trips from date_debut to date_fin
Trips_per_week7 = table_dates[(table_dates['date']>= date_debut) & (table_dates['date']<= date_fin)]
Trips_per_week7

,parent_station,date,arrival_time_max,arrival_time_min,stop_name,Amplitude en minutes
0,stop_area:SA_1,2023-08-07,73800.0,25200.0,Montjoie,8.035714
1,stop_area:SA_1,2023-08-08,73800.0,25200.0,Montjoie,8.035714
2,stop_area:SA_1,2023-08-09,73800.0,25200.0,Montjoie,8.035714
3,stop_area:SA_1,2023-08-10,73800.0,25200.0,Montjoie,8.035714
4,stop_area:SA_1,2023-08-11,73800.0,25200.0,Montjoie,8.035714
...,...,...,...,...,...,...
42710,stop_area:SA_999,2023-08-09,75180.0,20880.0,Lancefoc,8.978175
42711,stop_area:SA_999,2023-08-10,75180.0,20880.0,Lancefoc,8.978175
42712,stop_area:SA_999,2023-08-11,75180.0,20880.0,Lancefoc,8.978175
42713,stop_area:SA_999,2023-08-12,75180.0,20880.0,Lancefoc,8.978175
42714,stop_area:SA_999,2023-08-13,75000.0,24720.0,Lancefoc,8.313492

In [ ]:
Result = Trips_per_week7[['parent_station','stop_name','Amplitude en minutes']].groupby(['parent_station','stop_name']).sum().reset_index()
Result

         parent_station         stop_name  Amplitude en minutes
0        stop_area:SA_1          Montjoie             40.178571
1       stop_area:SA_10   Le Lac Reynerie             64.047619
2      stop_area:SA_100       Borde Haute             48.373016
3     stop_area:SA_1000           Phidias             53.730159
4     stop_area:SA_1002       Amidonniers             64.226190
...                 ...               ...                   ...
1747   stop_area:SA_994            Adonis             51.666667
1748   stop_area:SA_995  Gare de Lardenne             53.392857
1749   stop_area:SA_997       Centre Aéré             80.674603
1750   stop_area:SA_998     Ile du Ramier             80.128968
1751   stop_area:SA_999          Lancefoc             62.182540

[1752 rows x 3 columns]

Analyse de résultats

In [ ]:
Result.min()

parent_station          stop_area:SA_1
stop_name                  08 Mai 1945
Amplitude en minutes          5.912698
dtype: object

In [ ]:
Result.max()

parent_station          stop_area:SA_999
stop_name                         Zénith
Amplitude en minutes          106.160714
dtype: object

OLD CODE

In [ ]:
# Load GTFS data into DataFrames
calendar_df = pd.read_csv(r'C:\Users\sd\OneDrive\Indicateur TC\GTFS\calendar_dates.txt')
trips_df = pd.read_csv(r'C:\Users\sd\OneDrive\Indicateur TC\GTFS\trips.txt')
stop_times_df = pd.read_csv(r'C:\Users\sd\OneDrive\Indicateur TC\GTFS\stop_times.txt')
stops_df = pd.read_csv(r'C:\Users\sd\OneDrive\Indicateur TC\GTFS\stops.txt')

In [ ]:
# Merge the data to have the dates on it
merged_data = pd.merge(stop_times_df, calendar_df, on='service_id')

# Convert all dates to a consistent format (e.g., YYYY-MM-DD)
merged_data['date'] = pd.to_datetime(merged_data['date'], format='%Y%m%d', errors='coerce')

KeyError: 'service_id'

In [ ]:
target_stop_id = 'stop_point:SP_100'
# Find the stop of interest
target_stop = merged_data[merged_data['stop_id'] == target_stop_id]

In [ ]:
target_stop['date'] = pd.to_datetime(target_stop['date'], format='%Y%m%d', errors='coerce')

target_stop_weekly = target_stop[(target_stop['date']>='2023-08-07') & (target_stop['date']<='2023-08-13')]
target_stop_weekly.sort_values('arrival_time')

C:\Users\sd\AppData\Local\Temp\ipykernel_22716\3147941128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  target_stop['date'] = pd.to_datetime(target_stop['date'], format='%Y%m%d', errors='coerce')

,trip_id,arrival_time,departure_time,stop_id,pickup_type,drop_off_type,stop_sequence,shape_dist_traveled,timepoint,stop_headsign,...,shape_id,date,exception_type,stop_code,stop_name,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding
2968553,1790321,06:32:00,06:32:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-12,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2969161,1794437,06:33:00,06:33:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-11,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2969160,1794437,06:33:00,06:33:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-10,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2969159,1794437,06:33:00,06:33:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-09,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2969158,1794437,06:33:00,06:33:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-08,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2968765,1791584,21:04:00,21:04:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-11,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2968824,1791950,21:04:00,21:04:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-12,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2968762,1791584,21:04:00,21:04:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-08,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2968761,1791584,21:04:00,21:04:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-07,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2
2968763,1791584,21:04:00,21:04:00,stop_point:SP_100,0,0,10,3518.874365,1,NaN,...,11048,2023-08-09,1,3490.0,De Pisan,43.629862,1.44833,0,stop_area:SA_1057,2